pendulage_accueil_homepage:
    path:     /
    defaults: { _controller: PendulageAccueilBundle:Default:index }

vingtCinq_lister:
    path:     /Lister
    defaults: { _controller: PendulageAccueilBundle:VingtCinq:Lister }

vingtCinq_remove:
    path:     /Remove
    defaults: { _controller: PendulageAccueilBundle:VingtCinq:Remove }

vingtCinq_add:
    path:     /Add
    defaults: { _controller: PendulageAccueilBundle:VingtCinq:Add }

vingtCinq_modifier:
    path:     /Modifier
    defaults: { _controller: PendulageAccueilBundle:VingtCinq:Modifier }

vingtCinq_find:
    path:     /Find
    defaults: { _controller: PendulageAccueilBundle:VingtCinq:Find }

vingtCinq_find_by:
    path:     /FindBy
    defaults: { _controller: PendulageAccueilBundle:VingtCinq:FindBy }

catenaire_lister:
    path:     /catenaire/Lister
    defaults: { _controller: PendulageAccueilBundle:Catenaire:Lister }

catenaire_add:
    path:     /catenaire/Add
    defaults: { _controller: PendulageAccueilBundle:Catenaire:Add }

catenaire_remove:
    path:     /catenaire/Remove
    defaults: { _controller: PendulageAccueilBundle:Catenaire:Remove }

catenaire_modifier:
    path:     /catenaire/Modifier
    defaults: { _controller: PendulageAccueilBundle:Catenaire:Modifier }

catenaire_find_by:
    path:     /catenaire/FindBy
    defaults: { _controller: PendulageAccueilBundle:Catenaire:FindBy }

support_add:
    path:     /support/add
    defaults: { _controller: PendulageAccueilBundle:Support:Add }

support_find:
    path:     /support/find
    defaults: { _controller: PendulageAccueilBundle:Support:Find }

support_remove:
    path:     /support/remove
    defaults: { _controller: PendulageAccueilBundle:Support:Remove }

support_add_gauche:
    path:     /support/addGauche
    defaults: { _controller: PendulageAccueilBundle:Support:AddGauche }

support_modif:
    path:     /support/modif
    defaults: { _controller: PendulageAccueilBundle:Support:Modif }
    
support_lister:
    path:     /support/lister
    defaults: { _controller: PendulageAccueilBundle:Support:Lister }
